# Configuration for an SQLite file
sqliteDB:
  dbConfigFile: /app/pab/configuration/preview/preview.db
  dbConfigPoolSize: 20

#postgresDB:
#  dbConfigUser: postgres
#  dbConfigPass: pairfymarketplace
#  dbConfigHost: 127.0.0.1
#  dbConfigPort: 5432
#  dbConfigDatabase: dbpreview
#  dbConfigPoolSize: 20
#  dbConfigMarconiFile: marconi.sqlite

pabWebserverConfig:
  baseUrl: http://localhost:9080
  staticDir: .
  permissiveCorsPolicy: False
  # Optional timeout (in seconds) for calls to endpoints that are not currently
  # available. If this is not set, calls to unavailable endpoints fail
  # immediately.
  endpointTimeout: 15
  # Optional timeout (in seconds) when querying the status of an invoked endpoint for
  # which the expected contract status must be set to Done.
  # If this is not set, the query will wait until the instance state is updated.
  waitStatusTimeout: 60
  enableMarconi: False
  # Configure the paths to the certificate and the private key file to enable HTTPS:
  # certificatePath: host.crt
  # keyPath: host.key

walletServerConfig:
  tag: RemoteWalletConfig
#  walletSettings:
#    baseUrl: http://localhost:8090

nodeServerConfig:
  pscNodeMode: AlonzoNode
  pscNodeServerConfig:
    nscBaseUrl: http://localhost:3001
    nscSocketPath: /app/node/configuration/preview/db/node.socket
    nscKeptBlocks: 50
    nscNetworkId: 2
    nscSlotConfig:
      scSlotZeroTime: 1596059091000 # Wednesday, July 29, 2020 21:44:51 - shelley launch time in milliseconds
      scSlotLength: 1000 # In milliseconds
    nscInitialTxWallets:
      - getWallet: 1
      - getWallet: 2
      - getWallet: 3

  # Which cardano-node to use
  # Options are
  # - MockNode          (plutus-apps internal mock version of the node)
  # - AlonzoNode        (cardano-node via socket connection)
  # - NoChainSyncEvents (no node for chain sync events)

chainIndexConfig:
  ciBaseUrl: http://localhost:9083
  ciWatchedAddresses: []

#blockfrostConfig:
#  bfTokenPath: ./preview/blockfrost.json

requestProcessingConfig:
  requestProcessingInterval: 1

#signingProcessConfig:
#  spBaseUrl: http://localhost:9084
#  spWallet:
#    getWallet: 1

metadataServerConfig:
  mdBaseUrl: http://localhost:9085

developmentOptions:
  pabRollbackHistory: null
  pabResumeFrom:
    {
      "tag": "Point",
      "pointBlockId": "71280d6494b91e1281c98534ec2a3ddc0552cb36ddc39bdaf625f31a29b5a01a",
      "pointSlot": { "getSlot": 45823002 },
    }

# Optional EKG Server Config
# ----
#  { "tag" : "PointAtGenesis" }

monitoringConfig:
  monitoringPort: 9090
