apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaConnector
metadata:
  name: debezium-connector-mysql
  labels:
    strimzi.io/cluster: debezium-connect-cluster
spec:
  class: io.debezium.connector.vitess.VitessConnector
  tasksMax: 1
  config:
    tasks.max: 1
    database.hostname: "10.99.28.58"
    database.port: 3306
    database.user: "marketplace"
    database.password: "password"
    database.server.id: 184054
    topic.prefix: mysql
    database.include.list: service_seller
    schema.history.internal.kafka.bootstrap.servers: kafka-cluster-kafka-bootstrap:9092,kafka-cluster-kafka-bootstrap:9092,kafka-cluster-kafka-bootstrap:9092
    schema.history.internal.kafka.topic: schema-changes.service_seller