apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: service-node-storage-class
provisioner: kubernetes.io/no-provisioner
volumeBindingMode: WaitForFirstConsumer
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: service-node-pv
  labels:
    type: local  
spec:
  storageClassName: "service-node-storage-class"
  capacity:
    storage: 50Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/mnt/data" 
  claimRef:
    name: service-node-pvc
    namespace: default       
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: service-node-pvc
spec:
  storageClassName: "service-node-storage-class"
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 50Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-node
spec:
  replicas: 1
  selector:
    matchLabels:
      role: service-node
  template:
    metadata:
      labels:
        role: service-node
    spec:
      containers:
        - name: service-node
          image: pairfy/service-node
          env:
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: NETWORK
              value: preview
            - name: PATH
              value: "/app/node:${PATH}"
            - name: CONFIG
              value: "/app/node/configuration/$(NETWORK)"
          resources:
            requests:
              memory: "556Mi"
          volumeMounts:
            - name: storage-volume  
              mountPath: "/app/node"            
      volumes:
        - name: storage-volume
          persistentVolumeClaim:
            claimName: service-node-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: service-node
spec:
  selector:
    role: service-node
  ports:
    - name: service-node
      protocol: TCP
      port: 3001
      targetPort: 3001
