apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: service-index-storage-class
provisioner: kubernetes.io/no-provisioner
volumeBindingMode: WaitForFirstConsumer
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: service-index-pv
  labels:
    type: local  
spec:
  storageClassName: "service-index-storage-class"
  capacity:
    storage: 60Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/mnt/data"
  claimRef:
    name: service-index-pvc
    namespace: default   
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: service-index-pvc
spec:
  storageClassName: "service-index-storage-class"
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 60Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-index
spec:
  replicas: 1
  selector:
    matchLabels:
      role: service-index
  template:
    metadata:
      labels:
        role: service-index
    spec:
      containers:
        - name: service-index
          image: pairfy/service-index                       
          env:
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: NETWORK
              value: preview                 
            - name: NETWORK_ID
              value: "2"         
            - name: CONFIG
              value: "/app/index/configuration/$(NETWORK)" 
            - name: PATH
              value: "/app/index:${PATH}"                   
            - name: SOCKET_PATH
              value: "/app/node/configuration/$(NETWORK)/db/node.socket"                             
          resources:
            requests:
              memory: "556Mi"
          volumeMounts:
            - name: storage-volume 
              mountPath: /app/index/configuration
            - name: node-volume
              mountPath: /app/node/configuration           
      volumes:
        - name: storage-volume
          persistentVolumeClaim:
            claimName: service-index-pvc
        - name: node-volume
          persistentVolumeClaim:
            claimName: service-node-pvc                    
---
apiVersion: v1
kind: Service
metadata:
  name: service-index
spec:
  selector:
    role: service-index
  ports:
    - name: service-index
      protocol: TCP
      port: 9083
      targetPort: 9083
