apiVersion: v1
kind: PersistentVolume
metadata:
  name: service-node-pv
spec:
  capacity:
    storage: 50Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: /node 
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: service-node-pvc
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 25Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-node
spec:
  replicas: 1
  selector:
    matchLabels:
      role: service-node
  template:
    metadata:
      labels:
        role: service-node
    spec:
      containers:
        - name: service-node
          image: pairfy/service-node
          volumeMounts:
            - mountPath: /node 
              name: storage-volume
          env:
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: NETWORK
              value: preview
            - name: PATH
              value: "/app/node:${PATH}"
            - name: CONFIG
              value: "/app/node/configuration/$(NETWORK)"
          resources:
            requests:
              memory: "556Mi"
      volumes:
        - name: storage-volume
          persistentVolumeClaim:
            claimName: service-node-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: service-node
spec:
  selector:
    role: service-node
  ports:
    - name: service-node
      protocol: TCP
      port: 3001
      targetPort: 3001
