# Configuration for an SQLite file
sqliteDB:
  dbConfigFile: app/pab/testnet/sqlite/pabtestnet.db
  dbConfigPoolSize: 20


#postgresDB:
 # dbConfigUser: debian
 # dbConfigPass: pairfy-marketplace
 # dbConfigHost: 127.0.0.1
  #dbConfigPort: 5432
  #dbConfigDatabase: pabtestnet
 # dbConfigPoolSize: 20
 # dbConfigMarconiFile: marconi.sqlite

pabWebserverConfig:
  baseUrl: http://localhost:9080
  staticDir: .
  permissiveCorsPolicy: False
  # Optional timeout (in seconds) for calls to endpoints that are not currently
  # available. If this is not set, calls to unavailable endpoints fail
  # immediately.
  endpointTimeout: 5
  # Optional timeout (in seconds) when querying the status of an invoked endpoint for
  # which the expected contract status must be set to Done.
  # If this is not set, the query will wait until the instance state is updated.
  waitStatusTimeout: 60
  enableMarconi: False
  # Configure the paths to the certificate and the private key file to enable HTTPS:
  # certificatePath: host.crt
  # keyPath: host.key

walletServerConfig:
  tag: LocalWalletConfig
  walletSettings:
    baseUrl: http://localhost:9081

nodeServerConfig:
  pscNodeMode: AlonzoNode
  pscNodeServerConfig:
    nscBaseUrl: http://localhost:9082
    nscSocketPath: app/pab/testnet/node.sock
    nscKeptBlocks: 100000
    nscNetworkId: 2
    nscSlotConfig:
      scSlotZeroTime: 1596059091000 # Wednesday, July 29, 2020 21:44:51 - shelley launch time in milliseconds
      scSlotLength: 1000 # In milliseconds
    nscInitialTxWallets:
      - getWallet: 1
      - getWallet: 2
      - getWallet: 3
      - getWallet: 4
      - getWallet: 5
      - getWallet: 6
      - getWallet: 7
      - getWallet: 8
      - getWallet: 9
      - getWallet: 10


  # Which cardano-node to use
  # Options are
  # - MockNode          (plutus-apps internal mock version of the node)
  # - AlonzoNode        (cardano-node via socket connection)
  # - NoChainSyncEvents (no node for chain sync events)


chainIndexConfig:
  ciBaseUrl: http://localhost:9083
  ciWatchedAddresses: []

requestProcessingConfig:
  requestProcessingInterval: 1

signingProcessConfig:
  spBaseUrl: http://localhost:9084
  spWallet:
    getWallet: 1

metadataServerConfig:
  mdBaseUrl: http://localhost:9085

developmentOptions:
  pabRollbackHistory: null
  pabResumeFrom:
    { "tag" : "PointAtGenesis" }
    # { "tag" : "Point"
    # , "pointBlockId" : "613d23b8df670e3692f4e4ab59b179778519de15999ee1a51077fcc02a48abaa"
    # , "pointSlot" : { "getSlot" : 45656608 }
    # }

# Optional EKG Server Config
# ----
# monitoringConfig:
#   monitoringPort: 9090
