name: publisher-store

on:
  push:
    branches:
      - main
    paths:
      - 'publisher-store/**'
      
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }} 
      - run: cd publisher-store && docker build -t pairfy/publisher-store .    
      - run: docker push pairfy/publisher-store
      - uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.OCEAN_API_TOKEN }}
      - run: doctl kubernetes cluster kubeconfig save k8arka
      - run: kubectl rollout restart sts publisher-store
